blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/noctalia-dev/noctalia-shell/discussions
    about: Please use Discussions for questions, bug reports, and feedback.
